controller_frequency: 5

TrajectoryPlannerROS:
  max_vel_x: 0.3 #1.0 #0.5
  min_vel_x: 0.1 #0.01
  max_vel_theta: 1.0 #1.57 #1.5

  min_in_place_vel_theta: 0.314

  acc_lim_theta: 2.0 #3.14
  acc_lim_x: 1.5
  acc_lim_y: 1.5

  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.1

  sim_time: 1.5

  vx_samples: 5.0
  vtheta_samples: 10.0

  meter_scoring: true
  pdist_scale: 3.5 #0.6
  gdist_scale: 0.8 #0.8
  occdist_scale: 0.02

  holonomic_robot: false
